# SwiftLint Configuration for Offline AI&ML Playground

# Paths to include/exclude
included:
  - Offline AI&ML Playground
  - Offline AI&ML PlaygroundTests
  - Offline AI&ML PlaygroundUITests
excluded:
  - .build
  - Pods
  - Carthage
  - Packages
  - "*/Generated"

# Rules configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

disabled_rules:
  - line_length # We'll handle this separately
  - trailing_whitespace # Can be annoying during development
  - todo # We want to keep TODOs
  - fixme # We want to keep FIXMEs

# Rule configurations
force_cast: error
force_try: error
force_unwrapping: error

implicitly_unwrapped_optional:
  severity: error
  mode: all_except_iboutlets

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ID
    - i
    - j
    - k
    - x
    - y
    - z

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 2
    error: 3

# Custom rules
custom_rules:
  no_print_statements:
    included: ".*\\.swift"
    excluded: ".*Test\\.swift"
    name: "Print Statements"
    regex: '\bprint\('
    message: "Print statements should be replaced with proper logging"
    severity: warning
    
  no_dispatch_queue_main_async:
    name: "DispatchQueue.main.async Usage"
    regex: 'DispatchQueue\.main\.async'
    message: "Prefer @MainActor or MainActor.run over DispatchQueue.main.async"
    severity: warning
    
  magic_numbers:
    name: "Magic Numbers"
    regex: '(case|return|let|var|=|==|!=|<|>|<=|>=|\+|-|\*|\/|%)\s+(0x[0-9a-fA-F]+|[0-9]{2,})\b'
    excluded: ".*Test\\.swift|.*Spec\\.swift|Constants\\.swift"
    message: "Consider extracting magic numbers to named constants"
    severity: warning

# Reporter type (xcode, json, csv, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"