//
//  ChatMessageView.swift
//  Offline AI&ML Playground
//
//  Created by Ruslan Popesku on 05.07.2025.
//  Copyright © 2025 Ruslan Popesku. All rights reserved.
//

import SwiftUI

// MARK: - Chat Message View
struct ChatMessageView: View {
    let message: ChatMessage
    
    var body: some View {
        HStack {
            if message.role == .user {
                Spacer()
                messageContent
                    .background(Color.blue.opacity(0.1))
                    .foregroundColor(.primary)
            } else {
                messageContent
                    .background(Color.gray.opacity(0.1))
                    .foregroundColor(.primary)
                Spacer()
            }
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 4)
    }
    
    private var messageContent: some View {
        VStack(alignment: message.role == .user ? .trailing : .leading, spacing: 4) {
            Text(message.content)
                .font(.body)
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(message.role == .user ? Color.blue.opacity(0.1) : Color.gray.opacity(0.1))
                .clipShape(RoundedRectangle(cornerRadius: 12))
            
            HStack {
                if message.role == .assistant, let modelUsed = message.modelUsed {
                    Text("Generated by \(modelUsed)")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                
                Spacer()
                
                Text(message.timestamp.formatted(date: .omitted, time: .shortened))
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
        .frame(maxWidth: .infinity * 0.75, alignment: message.role == .user ? .trailing : .leading)
    }
}

// MARK: - Preview
#Preview {
    VStack(spacing: 8) {
        ChatMessageView(message: ChatMessage(
            content: "Hello, how are you?",
            role: .user,
            timestamp: Date(),
            modelUsed: nil
        ))
        
        ChatMessageView(message: ChatMessage(
            content: "I'm doing well, thank you for asking! How can I help you today?",
            role: .assistant,
            timestamp: Date(),
            modelUsed: "Llama 3.2 3B"
        ))
        
        ChatMessageView(message: ChatMessage(
            content: "Can you help me with a coding problem?",
            role: .user,
            timestamp: Date(),
            modelUsed: nil
        ))
        
        ChatMessageView(message: ChatMessage(
            content: "💻 As a code-focused model, I can help you with your coding problem. Here's my analysis:\n\n```swift\n// Swift example\nfunc solution() {\n    // Your implementation\n}\n```",
            role: .assistant,
            timestamp: Date(),
            modelUsed: "CodeLlama 7B"
        ))
    }
    .padding()
} 